//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Pointage.client.odooNS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="odooNS.odooWS")]
    public interface odooWS {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:odooWS/pointer", ReplyAction="urn:odooWS/pointerResponse")]
        System.IAsyncResult Beginpointer(string email, string pwd, System.AsyncCallback callback, object asyncState);
        
        string Endpointer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:odooWS/pointer2", ReplyAction="urn:odooWS/pointer2Response")]
        System.IAsyncResult Beginpointer2(int user_id, string login, System.AsyncCallback callback, object asyncState);
        
        string Endpointer2(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:odooWS/pointerLog", ReplyAction="urn:odooWS/pointerLogResponse")]
        System.IAsyncResult BeginpointerLog(string email, System.AsyncCallback callback, object asyncState);
        
        void EndpointerLog(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface odooWSChannel : Pointage.client.odooNS.odooWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class pointerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public pointerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class pointer2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public pointer2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class odooWSClient : System.ServiceModel.ClientBase<Pointage.client.odooNS.odooWS>, Pointage.client.odooNS.odooWS {
        
        private BeginOperationDelegate onBeginpointerDelegate;
        
        private EndOperationDelegate onEndpointerDelegate;
        
        private System.Threading.SendOrPostCallback onpointerCompletedDelegate;
        
        private BeginOperationDelegate onBeginpointer2Delegate;
        
        private EndOperationDelegate onEndpointer2Delegate;
        
        private System.Threading.SendOrPostCallback onpointer2CompletedDelegate;
        
        private BeginOperationDelegate onBeginpointerLogDelegate;
        
        private EndOperationDelegate onEndpointerLogDelegate;
        
        private System.Threading.SendOrPostCallback onpointerLogCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public odooWSClient() {
        }
        
        public odooWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public odooWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public odooWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public odooWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<pointerCompletedEventArgs> pointerCompleted;
        
        public event System.EventHandler<pointer2CompletedEventArgs> pointer2Completed;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> pointerLogCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Pointage.client.odooNS.odooWS.Beginpointer(string email, string pwd, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginpointer(email, pwd, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string Pointage.client.odooNS.odooWS.Endpointer(System.IAsyncResult result) {
            return base.Channel.Endpointer(result);
        }
        
        private System.IAsyncResult OnBeginpointer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string email = ((string)(inValues[0]));
            string pwd = ((string)(inValues[1]));
            return ((Pointage.client.odooNS.odooWS)(this)).Beginpointer(email, pwd, callback, asyncState);
        }
        
        private object[] OnEndpointer(System.IAsyncResult result) {
            string retVal = ((Pointage.client.odooNS.odooWS)(this)).Endpointer(result);
            return new object[] {
                    retVal};
        }
        
        private void OnpointerCompleted(object state) {
            if ((this.pointerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.pointerCompleted(this, new pointerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void pointerAsync(string email, string pwd) {
            this.pointerAsync(email, pwd, null);
        }
        
        public void pointerAsync(string email, string pwd, object userState) {
            if ((this.onBeginpointerDelegate == null)) {
                this.onBeginpointerDelegate = new BeginOperationDelegate(this.OnBeginpointer);
            }
            if ((this.onEndpointerDelegate == null)) {
                this.onEndpointerDelegate = new EndOperationDelegate(this.OnEndpointer);
            }
            if ((this.onpointerCompletedDelegate == null)) {
                this.onpointerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnpointerCompleted);
            }
            base.InvokeAsync(this.onBeginpointerDelegate, new object[] {
                        email,
                        pwd}, this.onEndpointerDelegate, this.onpointerCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Pointage.client.odooNS.odooWS.Beginpointer2(int user_id, string login, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginpointer2(user_id, login, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string Pointage.client.odooNS.odooWS.Endpointer2(System.IAsyncResult result) {
            return base.Channel.Endpointer2(result);
        }
        
        private System.IAsyncResult OnBeginpointer2(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int user_id = ((int)(inValues[0]));
            string login = ((string)(inValues[1]));
            return ((Pointage.client.odooNS.odooWS)(this)).Beginpointer2(user_id, login, callback, asyncState);
        }
        
        private object[] OnEndpointer2(System.IAsyncResult result) {
            string retVal = ((Pointage.client.odooNS.odooWS)(this)).Endpointer2(result);
            return new object[] {
                    retVal};
        }
        
        private void Onpointer2Completed(object state) {
            if ((this.pointer2Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.pointer2Completed(this, new pointer2CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void pointer2Async(int user_id, string login) {
            this.pointer2Async(user_id, login, null);
        }
        
        public void pointer2Async(int user_id, string login, object userState) {
            if ((this.onBeginpointer2Delegate == null)) {
                this.onBeginpointer2Delegate = new BeginOperationDelegate(this.OnBeginpointer2);
            }
            if ((this.onEndpointer2Delegate == null)) {
                this.onEndpointer2Delegate = new EndOperationDelegate(this.OnEndpointer2);
            }
            if ((this.onpointer2CompletedDelegate == null)) {
                this.onpointer2CompletedDelegate = new System.Threading.SendOrPostCallback(this.Onpointer2Completed);
            }
            base.InvokeAsync(this.onBeginpointer2Delegate, new object[] {
                        user_id,
                        login}, this.onEndpointer2Delegate, this.onpointer2CompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Pointage.client.odooNS.odooWS.BeginpointerLog(string email, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginpointerLog(email, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Pointage.client.odooNS.odooWS.EndpointerLog(System.IAsyncResult result) {
            base.Channel.EndpointerLog(result);
        }
        
        private System.IAsyncResult OnBeginpointerLog(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string email = ((string)(inValues[0]));
            return ((Pointage.client.odooNS.odooWS)(this)).BeginpointerLog(email, callback, asyncState);
        }
        
        private object[] OnEndpointerLog(System.IAsyncResult result) {
            ((Pointage.client.odooNS.odooWS)(this)).EndpointerLog(result);
            return null;
        }
        
        private void OnpointerLogCompleted(object state) {
            if ((this.pointerLogCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.pointerLogCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void pointerLogAsync(string email) {
            this.pointerLogAsync(email, null);
        }
        
        public void pointerLogAsync(string email, object userState) {
            if ((this.onBeginpointerLogDelegate == null)) {
                this.onBeginpointerLogDelegate = new BeginOperationDelegate(this.OnBeginpointerLog);
            }
            if ((this.onEndpointerLogDelegate == null)) {
                this.onEndpointerLogDelegate = new EndOperationDelegate(this.OnEndpointerLog);
            }
            if ((this.onpointerLogCompletedDelegate == null)) {
                this.onpointerLogCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnpointerLogCompleted);
            }
            base.InvokeAsync(this.onBeginpointerLogDelegate, new object[] {
                        email}, this.onEndpointerLogDelegate, this.onpointerLogCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Pointage.client.odooNS.odooWS CreateChannel() {
            return new odooWSClientChannel(this);
        }
        
        private class odooWSClientChannel : ChannelBase<Pointage.client.odooNS.odooWS>, Pointage.client.odooNS.odooWS {
            
            public odooWSClientChannel(System.ServiceModel.ClientBase<Pointage.client.odooNS.odooWS> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult Beginpointer(string email, string pwd, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = email;
                _args[1] = pwd;
                System.IAsyncResult _result = base.BeginInvoke("pointer", _args, callback, asyncState);
                return _result;
            }
            
            public string Endpointer(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("pointer", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult Beginpointer2(int user_id, string login, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = user_id;
                _args[1] = login;
                System.IAsyncResult _result = base.BeginInvoke("pointer2", _args, callback, asyncState);
                return _result;
            }
            
            public string Endpointer2(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("pointer2", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginpointerLog(string email, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = email;
                System.IAsyncResult _result = base.BeginInvoke("pointerLog", _args, callback, asyncState);
                return _result;
            }
            
            public void EndpointerLog(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("pointerLog", _args, result);
            }
        }
    }
}
